services:
  airflow_core:
    image: apache/airflow:2.11.0
    environment:
      - RUTAVOLUMES=${RUTAVOLUMES}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+pymysql://airflow:airflow@mysql:3306/airflow
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    volumes:
      - ${RUTAVOLUMES}/airflow:/opt/airflow
    ports:
      - "8080:8080"
    restart: unless-stopped

  airflow_mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=airflow
      - MYSQL_DATABASE=airflow
      - MYSQL_USER=airflow
      - MYSQL_PASSWORD=airflow
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
