services:
  airflow_core:
    image: apache/airflow:2.11.0
    environment:
      - RUTAVOLUMES=${RUTAVOLUMES}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    volumes:
      - ${RUTAVOLUMES}/airflow:/opt/airflow
    ports:
      - "8080:8080"
    restart: unless-stopped

  airflow_postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - ${RUTAVOLUMES}/postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
