services:
  airflow_core_2_11:
    image: apache/airflow:2.11.0
    environment:
      - RUTAVOLUMES=${RUTAVOLUMES}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres_2_11:5432/airflow2_11
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    volumes:
      - ${RUTAVOLUMES}/airflow:/opt/airflow
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
               airflow scheduler & airflow webserver"

  airflow_core_3:
    image: apache/airflow:3.0.0
    environment:
      - RUTAVOLUMES=${RUTAVOLUMES}
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres_3:5433/airflow3
      - AIRFLOW__DATABASE__LOAD_DEFAULT_CONNECTIONS=False
    volumes:
      - ${RUTAVOLUMES}/airflow3:/opt/airflow
    ports:
      - "8081:8080"
    restart: unless-stopped
    command: >
      bash -c "airflow db upgrade &&
               airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@example.com &&
               airflow scheduler & airflow api"

  airflow_postgres_2_11:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow2_11
    volumes:
      - ${RUTAVOLUMES}/postgres_data_2_11:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  airflow_postgres_3:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow3
    volumes:
      - ${RUTAVOLUMES}/postgres_data_3:/var/lib/postgresql/data
    ports:
      - "5433:5432"