services:
  airflow:
    image: apache/airflow:2.11.0
    environment:
      - RUTAVOLUMES=${RUTAVOLUMES}
    volumes:
      - ${RUTAVOLUMES}/airflow:/opt/airflow
    ports:
      - "8080:8080"
    restart: unless-stopped