name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Unlock macOS keychain
        run: security -v unlock-keychain -p $KEYCHAIN_PASSWORD ~/Library/Keychains/login.keychain-db
        env:
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
          RUTA_COMPOSES: ${{ secrets.RUTA_COMPOSES }}

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Ejecutar despliegue
        run: |
          set -x
          cd $RUTA_COMPOSES
          echo "Ruta de los repos: $RUTA_COMPOSES"
          git pull --recurse-submodules

          cd docker

          files=(docker-compose*.yml)
          args=()
          for f in "${files[@]}"; do
            args+=( -f "$f" )
          done

          docker compose "${args[@]}" down || true
          docker compose "${args[@]}" build --pull --no-cache
          docker compose "${args[@]}" up -d --force-recreate --remove-orphans
