name: Discovery gu Paths

on:
  workflow_dispatch:

jobs:
  discover:
    runs-on: self-hosted
    steps:
      - name: Inspect running containers
        run: |
          echo "Inspeccionando los contenedores actuales para ver sus rutas de origen..."
          docker ps --format "{{.Names}}" | while read container; do
            echo "--- $container ---"
            docker inspect $container | grep -i "working_dir" || true
          done
